[package]
name = "divivi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "divivi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
